[package]
name = "ipcon-sys"
version = "0.1.0"
authors = ["Seimizu Joukan <saimizi@gmail.com>"]
edition = "2018"
repository = "git@gitlab.com:joukan/ipcon-sys.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ipcon_sys"
path = "src/lib.rs"

[[bin]]
name = "ripcon_cmd"
path = "src/ripcon_cmd.rs"

[[bin]]
name = "ripcon_logger"
path = "src/ripcon_logger.rs"

[[bin]]
name = "ripcon_wait"
path = "src/ripcon_wait.rs"

[dependencies]
libc = "0.2.88"
getopts = "0.2.21"
env_logger = "0.8.3"
log = "0.4.14"
bytes = "1.0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
bincode = "1.3.2"
