[package]
name = "ipcon-sys"
version = "0.1.0"
authors = ["Seimizu Joukan <saimizi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "ipcon_sys"
path = "src/lib.rs"

[[bin]]
name = "ripcon_cmd"
path = "src/ripcon_cmd.rs"

[dependencies]
libc = "0.2.88"
getopts = "0.2.21"
env_logger = "0.8.3"
log = "0.4.14"
bytes = "1.0.1"
